### ISSUE TITLE
Create stand-alone docker-compose installation method

### ISSUE THREAD

**Issue by joshuakohut77** [starsoccer/ecosense#3]
Not all versions of home assistant have access to add-ons. Only Home Assistant Operating System or Home Assistant Supervised installation have access. It would be great to be able to run this as a stand alone docker container. If it already supports that could we get an example docker-compose yaml that we can run? Love the project, thanks for doing this!

**Comment by starsoccer** [comment]
It should be possible to run this as a standalone docker container and not an addon. Looking briefly there are only 2 things you should need to do:

1. Forward port 443. By default that container is listening on 443 so you need to either pass that through to the host, or use a different port and have another service like nginx proxy forward to that port
2. You will need to manually create the configuration file that Home Assistant generate automatically. That file is created at, `/data/options.json` and the schema can be seen here, https://github.com/starsoccer/ecosense/blob/master/ecosense/config.yaml#L10. You should be able to just make a json file locally and then map it as a volume or path with docker.

Example config below:
```
{
    "port": 443,
    "log_level": "trace",
    "dns_refresh_frequency": 180,
    "mqtt_host": "mqtt server ip or domain name",
    "mqtt_port": "1883",
    "mqtt_username": "username",
    "mqtt_password": "password"
}
```

If you need further help let me know. Assuming the above works let me know and Ill also add this to the readme

**Comment by joshuakohut77** [comment]
So I've made some progress but something's not working right. It could easily be my fault but I'll share where I'm at anyways. 

I created the `/data/options.json` file on my local machine and mapped it in as a path. The file has my mqtt credentials correctly. 

I use MQTT for a lot of devices so I'm confident this part is working with home assistant. 

When I start the container, this is the logs that I get. 
```
ecosense    | Setting ENV Variables
ecosense    | Env Set
ecosense    | Listing Versions!
ecosense    | Node Version: v22.13.1
ecosense    | NPM Version: 10.9.2
ecosense    | Starting Server
ecosense    | {"level":20,"time":1738355392450,"pid":20,"hostname":"483f05d68d2e","message":"Loaded Config"}
ecosense    | {"level":30,"time":1738355392980,"pid":20,"hostname":"483f05d68d2e","message":"Server listening on 443"}
ecosense    | {"level":20,"time":1738355393081,"pid":20,"hostname":"483f05d68d2e","message":"Ecosense IP Updated","ip":"3.167.112.14"}
```
So all that seems good to me however I'm not sure if I'm expecting to see other logs or not. 

The last part is doing the DNS rewrite. I have this setup through AdGuard Home. For Domain `api.cloud.ecosense.io` I answer it with my reverse proxy web page which is setup to use port 443. 

So as far as I can tell everything is setup correctly. However I'm not getting any entities made in home assistant, but maybe it's waiting on any kind of data before doing so. 

Lastly I assume my EcoQube device is working correctly because I was getting data reported before and now when I go into the app, it says I have no devices connected. This is probably because of the DNS rewrite. 

Here's my docker compose file with my reverse proxy details stripped out:
```
version: '3.8'

services:
  ecosense:
    image: "ghcr.io/starsoccer/ecosense/amd64"
    container_name: ecosense
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ecosense.loadbalancer.server.port=443"
      - "traefik.http.routers.ecosense.entrypoints=https"
      - "traefik.http.routers.ecosense.rule=xxxxxxxxxxxxxxxxxx"
      - "traefik.http.routers.ecosense.tls=true"
      - "traefik.http.routers.ecosense.tls.certresolver=xxxxxxxxxxxxxxxxxx"
      - "traefik.http.routers.ecosense.tls.options=xxxxxxxxxxxxxxxxxx"
      - "traefik.http.routers.ecosense.middlewares=xxxxxxxxxxxxxxxxxx"
    volumes:
      - ./data:/data
    networks:
      - ecosense

networks:
  ecosense:
    external: true
```
